base_images:
  ansible_operator:
    cluster: https://api.ci.openshift.org
    name: "4.4"
    namespace: ocp
    tag: ansible-operator
build_root:
  project_image:
    dockerfile_path: build/custom-ci-build-root.Dockerfile
images:
- dockerfile_path: build/Dockerfile
  from: ansible_operator
  to: template-service-broker-operator
promotion:
  name: "4.4"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.4"
  namespace: ocp
test_binary_build_commands: make openshift-ci-test-container
tests:
- as: lint
  commands: make openshift-ci-operator-lint
  container:
    from: test-bin
- as: operator-molecule-e2e
  commands: |
    NSS_WRAPPER_PASSWD=/tmp/passwd.nss_wrapper
    NSS_WRAPPER_GROUP=/etc/group
    cp /etc/passwd $NSS_WRAPPER_PASSWD
    echo "${USER:-default}:x:$(id -u):$(id -g):Default User:$HOME:/sbin/nologin" >> $NSS_WRAPPER_PASSWD
    export NSS_WRAPPER_PASSWD
    export NSS_WRAPPER_GROUP
    LD_PRELOAD=/usr/lib64/libnss_wrapper.so
    export LD_PRELOAD
    export LC_ALL=en_US.utf8
    export LANG=en_US.utf8
    molecule test -s cluster
  openshift_installer_src:
    cluster_profile: aws
- as: operator-molecule-olm-e2e
  commands: |
    NSS_WRAPPER_PASSWD=/tmp/passwd.nss_wrapper
    NSS_WRAPPER_GROUP=/etc/group
    cp /etc/passwd $NSS_WRAPPER_PASSWD
    echo "${USER:-default}:x:$(id -u):$(id -g):Default User:$HOME:/sbin/nologin" >> $NSS_WRAPPER_PASSWD
    export NSS_WRAPPER_PASSWD
    export NSS_WRAPPER_GROUP
    LD_PRELOAD=/usr/lib64/libnss_wrapper.so
    export LD_PRELOAD
    export LC_ALL=en_US.utf8
    export LANG=en_US.utf8
    molecule test -s cluster-olm
  openshift_installer_src:
    cluster_profile: aws
